import type { Metadata } from "next";
import { baiJamjuree } from "./fonts";
import "./globals.css";
import StoreProvider from "./StoreProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="th">
      <body className={baiJamjuree.className}>
        <StoreProvider>{children}</StoreProvider>
      </body>
    </html>
  );
}
